Some questions, that have come up several times in various discussions.

I want to help by translating Thonny UI or webpage to another language. How should I start?
--------------------------------------------------------------------------------------------
See `Translations <Translations>`_

We're glad to add links to tutorials / help / documentation written in other languages.

*A related issue: Thonny's main developers are not native English speakers. Feel free to suggest corrections for grammar / spelling / style.*

