For users:

* `Changelog <https://github.com/thonny/thonny/blob/master/CHANGELOG.rst>`_
* `FAQ <FAQ>`_
* `Using Thonny on Mac OS X <MacOSX>`_
* `Using Thonny on Windows <Windows>`_
* `Using Thonny on Linux <Linux>`_
* `Classroom usage / deployment options <DeploymentOptions>`_
* `Installing Thonny to an existing Python <SeparateInstall>`_
* `Installing extra packages <InstallingPackages>`_
* `Using Thonny for MicroPython <MicroPython>`_

For contributors:

* `Overview <https://github.com/thonny/thonny/blob/master/CONTRIBUTING.rst>`_
* `Running Thonny from the source <Running-from-the-source>`_
* `Writing plug-ins <Plugins>`_
* `Writing themes (as plug-ins) <Theming>`_

[testing]