If there is no Thonny+Python bundle for your operating system, or you can't, or don't want to use it, you can first install Python (or use your existing Python) and then install Thonny in the context of this Python installation.

General steps
--------------

1. Install Python 3.5 or later (or choose an existing installation).
2. Install Thonny package with ``pip`` (possibly ``pip3``) using your operating system command line.
3. Run Thonny package.


Windows
-------
See `Windows <Windows>`_

Mac OS X
-----------
If you don't have Python 3.5 or later installed, go to https://www.python.org/downloads/mac-osx/ and install the latest Python from there. (NB! Thonny requires Python which is linked to Tk 8.6. Python installers provided at www.python.org are suitable.)

For installing Thonny as a package, you need to go to the system command line and execute something like ``pip install thonny``, but you need to make sure command ``pip`` is related to correct Python installation.

For opening system command line: 

1. open Finder
2. from the menu choose Go => Utilities
3. open "Terminal"

Assuming you are using official Python 3.7 distribution, paste following into Terminal and press ENTER:

.. sourcecode:: bash

    /Library/Frameworks/Python.framework/Versions/3.7/bin/pip3.7 install thonny

You should see something like this:

.. image:: https://bitbucket.org/repo/gXnbod/images/4031047622-Screen%20Shot%202015-11-26%20at%2014.24.23.png
   :alt: Screen Shot 2015-11-26 at 14.24.23.png

Now you can run Thonny with following command:

.. sourcecode:: bash

    /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -m thonny