Thonny will be translatable in version 3.2

Instructions: https://github.com/thonny/thonny/blob/master/docs/translate.md

Discussion: https://github.com/thonny/thonny/issues/668

**NB! At the moment only part of the UI strings are marked as translatable.** Help is welcome here!

**NB! Don't expect the source strings to remain stable across Thonny versions!** If a string that you've translated seems to been reverted to English in next version, then the source string was probably updated and you need look it up and translate again in the POEditor.